### ISSUE TITLE
Strong typing of introspection API vs. missing class knowledge

### ISSUE THREAD

**Issue by may-bee** [m-m-m/util#129]
I like the approach of strict typing the API. But nevertheless, this will not come without pitfalls.
I try to implement IMHO the often occuring process of introspecting a class of an unknown type (`Class<?>`).
Using the `ProjoDescriptorBuilder#getDescriptor(Class<POJO>)` method with the input of type `Class<?>`, the compiler will set the PojoDescriptorBuilder type parameter `POJO` to an arbitrary but fixed type capture, lets name it `x`.

This type parameter will be the bases of further creation of e.g. `PojoPropertyDescriptor`s. When I now try to get a property by its name using the method `Object getProperty(POJO pojo, String property)` 
the previously fixed type capture `x` will not match any input. Especially, the same input parameter of type `Class<?>` as previously used to create the builder. The compiler will label the type capture of the current but same method parameter different, e.g. `y`. So you will get a type mismatch compiler error.

If you are interested, we should investigate, whether we can provide an additional API, which is less type safe than the current one. But due to work on the harmcrest library, I could also imagine that this might be a hard job.

**Comment by hohwille** [comment]
No reaction for several month. Workaround is still valid:
>  Class&lt;?> type = TestPojo.class;
PojoDescriptor pojoDescriptor = builder.getDescriptor(type);
foo = pojoDescriptor.getProperty(pojoInstance, "foo");

Works fine. The Problem only occurs when you use ```PojoDescriptor<?>``` instead.
