### ISSUE TITLE
mmm-util-core: GWT l10n support for deserialized NlsMessage 

### ISSUE THREAD

**Issue by hohwille** [m-m-m/util#141]
As described in #113 instances of NlsMessage that have been transferred from the server to the client can not be properly localized on the client. This is quite a tricky, special and questionable use-case after all. Please let us know, if you are expecting this support...

**Comment by may-bee** [comment]
I do not think this is necessary as long as the messages come up with a unique id as for usability reasons a client will rewrite messages most properly (and non-technically) to their occurence anyway.
For clients, which do not provide any output of the messages to any user, will not need any localization as the messages will be not more than logged, which should be done in english by default.

**Comment by hohwille** [comment]
Thanks for the feedback. GWT is especially only for SPA/RIA web clients. And this issue is about the fact that such client shall be able to rewrite the messages using his own bundles and his current language settings. If server and client are written from the same java codebase it is however expectable that the localization should somehow be possible after serialization to the client.

**Comment by hohwille** [comment]
modern world is using JSON. Who cares about such special features of special serialization?
If you do please comment and we can consider reopening....
