### ISSUE TITLE
duplicate accessor log messages of PojoDescriptorBuilder

### ISSUE THREAD

**Issue by maybeec** [m-m-m/util#241]
Currently, I observe quite often messages like

`15:54:47.834 [ModalContext] [C:132604f3-0618-46bb-8d37-4b30a59f4981] - DEBUG - n.s.m.u.p.d.i.PojoDescriptorBuilderImpl - accessor 'get-accessor of property 'AbstractPersistenceEntity.id' with type java.lang.Object' - is a duplicate of 'get-accessor of property 'AbstractPersistenceEntity.id' with type java.lang.Long'!`

Due to our last discussion, this the error message is misleading the user to the need of adapting his code somehow. As far as I got you right, it is more an issue of the java reflection API. So it might be up to discussion whether to remove this message entirely or put it on trace as there might be very raw cases in which you even want to see this information, which might already produce a large amount of log messages depending on the code size you inspect.

**Comment by hohwille** [comment]
Thanks for your feedback. Changed loglevel to trace so users do not need to bother. Also merged to develop.
